#!/bin/bash
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_01 AGTGCC 1 C57WPANXX 7 2014-09-25 01-1
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_02 CATTAG 1 C57WPANXX 7 2014-09-26 01-2
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_03 CGATGT 1 C57WPANXX 7 2014-09-27 01-3
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_04 TGACCA 1 C57WPANXX 7 2014-09-28 01-4
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_05 GCCAAT 1 C57WPANXX 7 2014-09-29 01-5
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_06 CTTGTA 1 C57WPANXX 7 2014-09-30 01-6
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_07 ATCACG 1 C57WPANXX 7 2014-09-31 01-7
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_01_08 TTAGGC 1 C57WPANXX 7 2014-09-32 01-8
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_01 ACTTGA 1 C57WPANXX 7 2014-09-33 95-1
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_02 GATCAG 1 C57WPANXX 7 2014-09-34 95-2
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_03 TAGCTT 1 C57WPANXX 7 2014-09-35 95-3
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_04 GGCTAC 1 C57WPANXX 7 2014-09-36 95-4
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_05 AGTCAA 1 C57WPANXX 7 2014-09-37 95-5
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_06 AGTTCC 1 C57WPANXX 7 2014-09-38 95-6
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_07 ATGTCA 1 C57WPANXX 7 2014-09-39 95-7
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_95_08 CCGTCC 1 C57WPANXX 7 2014-09-40 95-8
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_01 GTCCGC 1 C57WPANXX 7 2014-09-41 14-1
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_02 GTGAAA 1 C57WPANXX 7 2014-09-42 14-2
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_03 GTGGCC 1 C57WPANXX 7 2014-09-43 14-3
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_04 GTTTCG 1 C57WPANXX 7 2014-09-44 14-4
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_05 CGTACG 1 C57WPANXX 7 2014-09-45 14-5
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_06 GAGTGG 1 C57WPANXX 7 2014-09-46 14-6
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_07 ACTGAT 1 C57WPANXX 7 2014-09-47 14-7
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane7.indexlength_6/Fastq AU_14_08 ATTCCT 1 C57WPANXX 7 2014-09-48 14-8
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_01 AGTGCC 2 C57WPANXX 8 2014-09-49 01-1
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_02 CATTAG 2 C57WPANXX 8 2014-09-50 01-2
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_03 CGATGT 2 C57WPANXX 8 2014-09-51 01-3
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_04 TGACCA 2 C57WPANXX 8 2014-09-52 01-4
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_05 GCCAAT 2 C57WPANXX 8 2014-09-53 01-5
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_06 CTTGTA 2 C57WPANXX 8 2014-09-54 01-6
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_07 ATCACG 2 C57WPANXX 8 2014-09-55 01-7
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_01_08 TTAGGC 2 C57WPANXX 8 2014-09-56 01-8
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_01 ACTTGA 2 C57WPANXX 8 2014-09-57 95-1
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_02 GATCAG 2 C57WPANXX 8 2014-09-58 95-2
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_03 TAGCTT 2 C57WPANXX 8 2014-09-59 95-3
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_04 GGCTAC 2 C57WPANXX 8 2014-09-60 95-4
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_05 AGTCAA 2 C57WPANXX 8 2014-09-61 95-5
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_06 AGTTCC 2 C57WPANXX 8 2014-09-62 95-6
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_07 ATGTCA 2 C57WPANXX 8 2014-09-63 95-7
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_95_08 CCGTCC 2 C57WPANXX 8 2014-09-64 95-8
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_01 GTCCGC 2 C57WPANXX 8 2014-09-65 14-1
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_02 GTGAAA 2 C57WPANXX 8 2014-09-66 14-2
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_03 GTGGCC 2 C57WPANXX 8 2014-09-67 14-3
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_04 GTTTCG 2 C57WPANXX 8 2014-09-68 14-4
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_05 CGTACG 2 C57WPANXX 8 2014-09-69 14-5
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_06 GAGTGG 2 C57WPANXX 8 2014-09-70 14-6
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_07 ACTGAT 2 C57WPANXX 8 2014-09-71 14-7
sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/whole-genome-reseq/PreProcessing/01_run_FastqToAlignedBAM_AuburnInds.sbatch /n/holylfs/LABS/edwards_lab/ashultz/HFWGReseq/rawdata/AuburnRawData/Lane8.indexlength_6/Fastq AU_14_08 ATTCCT 2 C57WPANXX 8 2014-09-72 14-8
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     