#!/bin/bash

sbatch run_bwa_mem_serial.sh Au-01-1 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex 
sbatch run_bwa_mem_serial.sh Au-01-2 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-3 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-4 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-5 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-6 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-7 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-8 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-1 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-2 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-3 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-4 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-5 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-6 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-7 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-01-8 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-1 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-2 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-3 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-4 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-5 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-6 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-7 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-8 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-1 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-2 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-3 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-4 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-5 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-6 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-7 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-14-8 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-1 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-2 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-3 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-4 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-5 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-6 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-7 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-8 320 L7 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-1 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-2 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-3 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-4 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-5 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-6 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-7 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex
sbatch run_bwa_mem_serial.sh Au-95-8 320 L8 /n/regal/edwards_lab/hofi/AuburnWGReseq/genome/haeMex